services:
  mysql:
    image: mysql:8
    container_name: mysql-plumora
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: plumora
      MYSQL_USER: plumora
      MYSQL_PASSWORD: StrongPassword!123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-plumora
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: