"""add manuscripts tables

Revision ID: a217579f494e
Revises: 4d9d63d95a34
Create Date: 2026-03-15 12:39:51.908344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a217579f494e'
down_revision: Union[str, Sequence[str], None] = '4d9d63d95a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manuscripts',
    sa.Column('id', sa.String(length=36), nullable=False),
sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscripts_author_id'), 'manuscripts', ['author_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manuscript_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chapter_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manuscript_id', 'chapter_order', name='uq_chapter_order_per_manuscript')
    )
    op.create_index(op.f('ix_chapters_manuscript_id'), 'chapters', ['manuscript_id'], unique=False)
    op.create_table('manuscript_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manuscript_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title_snapshot', sa.String(length=255), nullable=False),
    sa.Column('synopsis_snapshot', sa.Text(), nullable=True),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manuscript_id', 'version_number', name='uq_version_number_per_manuscript')
    )
    op.create_index(op.f('ix_manuscript_versions_manuscript_id'), 'manuscript_versions', ['manuscript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manuscript_versions_manuscript_id'), table_name='manuscript_versions')
    op.drop_table('manuscript_versions')
    op.drop_index(op.f('ix_chapters_manuscript_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_manuscripts_author_id'), table_name='manuscripts')
    op.drop_table('manuscripts')
    # ### end Alembic commands ###
