"""add editorial dossiers table

Revision ID: a5f8fb43b1c3
Revises: a217579f494e
Create Date: 2026-03-15 14:38:42.573338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f8fb43b1c3'
down_revision: Union[str, Sequence[str], None] = 'a217579f494e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_dossiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manuscript_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_editor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submission_note', sa.Text(), nullable=True),
    sa.Column('editorial_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_editor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manuscript_id', name='uq_editorial_dossier_manuscript')
    )
    op.create_index(op.f('ix_editorial_dossiers_assigned_editor_id'), 'editorial_dossiers', ['assigned_editor_id'], unique=False)
    op.create_index(op.f('ix_editorial_dossiers_manuscript_id'), 'editorial_dossiers', ['manuscript_id'], unique=False)
    op.create_index(op.f('ix_editorial_dossiers_submitted_by_user_id'), 'editorial_dossiers', ['submitted_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editorial_dossiers_submitted_by_user_id'), table_name='editorial_dossiers')
    op.drop_index(op.f('ix_editorial_dossiers_manuscript_id'), table_name='editorial_dossiers')
    op.drop_index(op.f('ix_editorial_dossiers_assigned_editor_id'), table_name='editorial_dossiers')
    op.drop_table('editorial_dossiers')
    # ### end Alembic commands ###
